### PR TITLE
Changed name

### PR DESCRIPTION
**Pull request by tonynv**
Some details

### CODE REVIEW

**Review by andrew-glenn — CHANGES_REQUESTED** [review]
Has this gone through legal review?

**Comment by tonynv** [comment]
> Has this gone through legal review?

No not yet

**Comment by andrew-glenn** [comment]
> > Has this gone through legal review?
> 
> No not yet

Please email; legal@

**Review by andrew-glenn — APPROVED** [review]
Legal stuff hashed out. Good to go.

**Pull request merged**
